# Generated by Django 3.2.17 on 2025-06-21 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('healthy', 'Healthy'), ('risk', 'Risk'), ('under treatment', 'Under Treatment')], default='healthy', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('tag_number', models.CharField(max_length=250, unique=True)),
                ('date_of_birth', models.CharField(max_length=250)),
                ('image', models.ImageField(max_length=1000, upload_to='app/cow_images')),
                ('breed', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '03 Cow',
            },
        ),
        migrations.CreateModel(
            name='VaccineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_summarized_symptoms', models.CharField(blank=True, max_length=250, null=True)),
                ('symptoms_name', models.JSONField()),
                ('symptoms_base_on_time', models.CharField(max_length=250)),
                ('disease', models.CharField(max_length=250)),
                ('treatment_medication', models.CharField(max_length=250)),
                ('definition', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '04 Vaccine Event',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '01 User Profile',
            },
        ),
        migrations.CreateModel(
            name='Apparence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_theme', models.CharField(choices=[('Dark', 'Dark'), ('Ligth', 'Light'), ('System Color', 'System Color')], default='Ligth', max_length=50)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '02 Apparence',
            },
        ),
    ]
